feat: gzip dumps
gemini-testing/hermione-mocks pull request #5
Opened 2023-03-16 21:55 UTC by KuznetsovRoman

## Что сделано

Добавил сжатие на файлы с дампами. Теперь по умолчанию на файловую систему пишутся сжатые `.json.gz` файлы, и они же читаются.

По размеру разница где-то в 4 раза.

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/modes/readMode.ts
> +                _.set(store.currentTest, TEST_MOCKS_ERROR, error);
Раньше тут первоначальная ошибка скидывалась.

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/store.test.ts
> -            const dumpPath = path.resolve(process.cwd(), "specified", "uGDzURz0") + ".json";
Теперь расширение добавляется на уровне `readJson`, `readJsonGz`, `writeJson`, `writeJsonGz`

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/store.ts
> +        gzipDumps: boolean,
тут храним: "нужно ли сжимать дампы"

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/store.ts
> +        return base64.slice(0, 8).replace(/\//g, "#");
Теперь расширение добавляется на уровне `readJson`, `readJsonGz`, `writeJson`, `writeJsonGz`

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/__mocks__/streamMock.ts
> +class StreamMock {
Поскольку у `zlib` используется API c потоками, нужно было чем-то замокать его и потоковые методы `fs`. Поэтому создал этот класс

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/__mocks__/streamMock.ts
> +class StreamMock extends EventEmitter {
Поскольку у `zlib` используется потоковое API, чтобы протестировать код с ним и потоковыми операциями `fs`, нужен какой-нибудь эвент эмиттер. Вот это мок потоков для тестирования.

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/__mocks__/streamMock.ts
> +    }
Вот это вот нужно, чтобы было удобно тестировать: вызываем у замоканного потока `setPendingEvents` с эвентами, через которые он должен пройти в тестовых сценариях, и получаем возможность протестировать все сценарии

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/__mocks__/streamMock.ts
> +    private emitListening(): void {
Тут просто по очереди вызываем обработчики, если они есть. То есть, если в очереди обработчики эвентов `["foo", "bar", "baz"]`, а в коде они добавляются в порядке `["bar", "foo"]`, то обработчики `["foo", "bar"]` будут выполнены оба после добавления обработчика `foo`

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/fileUtils.test.ts
> +        writeFile: jest.fn().mockReturnValue(Promise.resolve()),
Пустой `mockResolvedValue` вызвать нельзя

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/fileUtils.test.ts
> +        gzipMock.pipe.mockReturnValue(writePipeMock);
вот эти вот потоки используются в коде.

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/worker.ts
> +export const writeDump: writeDump = async (fileName, dump, { gzipDumps = true, overwrite } = {}) => {
Выполняет все проверки, затем пишет жсон с помощью одной из функций

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/store.test.ts
> +                    expect.objectContaining({ overwrite: state }),
Тест про `overwrite`, тут не должно интересовать, какое значение у `gzipDumps`, на это отдельный тест есть

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +    const data = JSON.stringify(dump, null, 2);
Вот тут форматируем с отступами, потому что это можно прочитать

2023-03-16 22:52 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +        const data = Buffer.from(JSON.stringify(dump));
Тут отступы в жсон-строке не нужны

2023-03-17 08:07 UTC, KuznetsovRoman commented on src/modes/readMode.ts
> +                _.set(store.currentTest, TEST_MOCKS_ERROR, error);
Напомню, что такое решение обработки ошибок тут используется потому что `throw` тут и в обработчике `targetcreated` `puppeteer`-a приводит к `unhandled rejection`, а метода браузера типа "упади с такой ошибкой" нет. Поэтому временное решение заключается в записи ошибки в тест, и затем сваливания теста в `hermione-interceptor`-ах

2023-03-17 10:35 UTC, shadowusr commented on package.json
> +        "zlib": "^1.0.5"
Хм, но ведь этот пакет не обновлялся более 12 лет, функциональность zlib есть в built-in'ах node: https://nodejs.org/docs/latest-v16.x/api/zlib.html#zlib

2023-03-17 10:44 UTC, shadowusr commented on src/store.ts
> +        gzipDumps: boolean,
Это не требует исправлений, просто зацепился взгляд:

Это не связано с PR, просто интересно, зачем вообще нам нужен create, который просто вызывает конструктор? Как правило делаем create, когда есть какая-то доп. асинхронная логика, которую не можем положить в конструктор.

Ну и в целом корректный тип возврата create – this, а не Store, потому что с текущими типами будут проблемы, если отнаследоваться от этого класса, create всегда будет возвращать только родительский класс.

2023-03-17 10:46 UTC, KuznetsovRoman commented on package.json
> +        "zlib": "^1.0.5"
И правда. Причем API идентичный, как будто `zlib` запихали целиком в `node`. Убрал `zlib` из зависимостей, работоспособность не изменилась.

2023-03-17 10:56 UTC, shadowusr commented on src/workers/fileUtils.ts
> +    const data = JSON.stringify(dump, null, 2);
х3. Я бы всегда в минифицированном виде писал. Нажать один хоткей в ide, чтобы отформатировать json вроде не сложно для пользователя, если это нужно будет. А так получается у нас неявно определяется разное поведение при записи и не факт, что формат нравится пользователю. Жестко хардкодим 2, хотя я, например, привык к 4 пробелам

2023-03-17 11:04 UTC, shadowusr commented on src/workers/fileUtils.ts
> +        const compress = zlib.createGzip();
Что-то не вижу тут профита работать со стримами. Прикол стримов, что работаем с данными почанково. Здесь же у нас в любом случае есть файл целиком и мы ждем, пока он запишется целиком. Поэтому я бы написал в 1 строку (не считая импортов) без всяких промисов и стримов:
```
import {gzip as gzipCallback} from "node:zlib";
import {promisify} from "util";
const gzip = promisify(zipCallback);

// ...
    return gzip(buffer);
// ...
```

2023-03-17 11:04 UTC, shadowusr commented on src/workers/fileUtils.ts
> +        const decompress = zlib.createGunzip();
Аналогичный вопрос насчет использования стримов, как в функции write

2023-03-17 11:12 UTC, shadowusr requested changes
Из важных замечаний:
- Надо избавиться от deprecated-зависимости zlib
- Нужно убедиться, что работа со стримами здесь действительно нужна

Тесты не смотрел, т.к. если отказаться от стримов, они становятся не актуальны

2023-03-17 11:20 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +        const compress = zlib.createGzip();
Я думал, что профит стримов в работе с большими файлами (а дамп на целый тест вполне таким может быть) в том, чтобы не грузить весь файл целиком, тем более, что `gzip` именно поточный архиватор, которому не нужен весь дамп целиком, чтобы его заархивировать

2023-03-17 11:23 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +        const decompress = zlib.createGunzip();
Интуитивно как-то кажется, что разархивировать данные сразу на лету будет как-то быстрее, чем:
- считать буфер целиком
- разархивировать
- распарсить

2023-03-17 13:36 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +    const data = JSON.stringify(dump, null, 2);
Поставил 4 пробела

> Нажать один хоткей в ide, чтобы отформатировать json

Я вот, например, про такой хоткей не знаю.

> неявно определяется разное поведение при записи

Делал из соображений, что по умолчанию эти дампы сжимаются, и если и есть причина, по которой это сжатие нужно отключить - то это как раз, чтоб посмотреть на то, что там вообще снимается. А для этого лучше пусть файлик будет отформатирован

Ну и этот неявный формат по идее не критичный, ведь даже если этот обычный жсон `gzip`-нуть, он нормально распарсится, ровно как и `gunzip`-нутый дамп, у которого этих отступов нет

2023-03-17 13:38 UTC, KuznetsovRoman commented on src/store.ts
> +        gzipDumps: boolean,
Видел его частенько в коде гермионы, вот и написал. Недавно Антон в своем пулл реквесте объяснил, зачем эти `create` нужны. Убрал.

2023-03-17 14:03 UTC, shadowusr commented on .eslintrc.js
> +            files: ["**/src/**/*.test.ts", "**/src/**/__mocks__/*.ts"],
Не критично, но получается, что это уже не нужно сейчас

2023-03-17 15:20 UTC, KuznetsovRoman commented on .eslintrc.js
> +            files: ["**/src/**/*.test.ts", "**/src/**/__mocks__/*.ts"],
Подумал, может понадобиться в будущем.

2023-03-22 13:20 UTC, shadowusr approved these changes

2023-03-22 13:23 UTC, merged

2023-03-22 18:53 UTC, DudaGod commented on src/workers/fileUtils.ts
> +import fs from "fs";
Мы обычно nodejs модули именуем без заглавных букв. Это же у тебя не реактовский компонент какой-то.

2023-03-22 18:55 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +import fs from "fs";
А где тут заглавные?

2023-03-22 18:56 UTC, DudaGod commented on src/workers/fileUtils.ts
> +import fs from "fs";
Под nodejs модулем я имел ввиду сам файл - `fileUtils.ts`, заглавная - `U`.

2023-03-22 19:01 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +import fs from "fs";
Назвал с camelCase по аналогии с `readMode.ts`, `writeMode.ts`, `hermioneMocksError.ts`

2023-03-22 19:04 UTC, DudaGod commented on src/workers/fileUtils.ts
> +import fs from "fs";
Значит не замечал до этого. Не предлагаю бежать переименовывать прям сейчас что-то. Просто jfyi.

2023-03-22 19:04 UTC, KuznetsovRoman commented on src/workers/fileUtils.ts
> +import fs from "fs";
Почему этот файл - `nodejs `модуль, а вот эти вот три - нет? Как то странно смешивать типы написания

2023-03-23 07:27 UTC, DudaGod commented on src/workers/fileUtils.ts
> +import fs from "fs";
Они все nodejs модули и все называются не правильно, т.е. не так как принято именовать в наших проектах. React компоненты именуем так - `MyComponent.tsx`. Все остальное через kebab case: `file-utils.ts`, `read-mode.ts`, `write-mode.ts`, `hermione-mocks-error.ts`.